apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: petclinic-prod

bases:
  - ../../base/mysql-azure
  - ../../base/petclinic

resources:
  - namespace.yaml

patchesJson6902:
  - target:
      group: apps.openshift.io
      version: v1
      kind: DeploymentConfig
      name: petclinic
    path: environment-patch.yaml