apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cicd

resources:
  - namespace.yaml
  - petclinic-imagestream.yaml
  - petclinic-buildconfig.yaml
  - image-puller-rolebinding.yaml

patchesJson6902:
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: RoleBinding
      name: cicd-image-puller
    path: image-puller-subjects-patch.yaml