apiVersion: azure.microsoft.com/v1alpha1
kind: ResourceGroup
metadata:
  name: openshift-databases
spec:
  location: "canadacentral"
---
apiVersion: azure.microsoft.com/v1alpha2
kind: MySQLServer
metadata:
  name: prod-mysql-aro
spec:  
  location: canadacentral
  resourceGroup: openshift-databases
  serverVersion: "8.0"
  sslEnforcement: Disabled
  createMode: Default # Possible values include: Default, Replica, PointInTimeRestore (not implemented), GeoRestore (not implemented)
  sku:
    name: B_Gen5_1 # tier + family + cores eg. - B_Gen4_1, GP_Gen5_4
    tier: Basic # possible values - 'Basic', 'GeneralPurpose', 'MemoryOptimized'
    family: Gen5 
    size: "51200"
    capacity: 1
---
apiVersion: azure.microsoft.com/v1alpha1
kind: MySQLDatabase
metadata:
  name: petclinic
spec:
  resourceGroup: openshift-databases
  server: prod-mysql-aro
---
apiVersion: azure.microsoft.com/v1alpha1
kind: MySQLFirewallRule
metadata:
  name: openshift-mysql-aro-fw
spec:
  resourceGroup: openshift-databases
  server: prod-mysql-aro
  startIpAddress: 0.0.0.0
  endIpAddress: 0.0.0.0
