apiVersion: v1
kind: Service
metadata:
  name: petclinicdb
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    name: petclinicdb
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
