apiVersion: v1
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  name: petclinicdb
type: Opaque
stringData:
  database-name: petclinic
  database-password: petclinic
  database-root-password: petclinic
  database-user: petclinic

